"""Reporting module for BugBounty MCP."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List, Optional

from ..models import Report, Severity, Vulnerability


class MarkdownReporter:
    """Generate Markdown vulnerability reports."""

    def generate(self, report: Report) -> str:
        """Generate a Markdown report."""
        lines = [
            f"# {report.title}",
            "",
            f"**Target:** {report.target}",
            f"**Date:** {report.created_at.strftime('%Y-%m-%d %H:%M:%S')}",
            f"**Version:** {report.version}",
            "",
        ]

        # Executive summary
        lines.extend([
            "## Executive Summary",
            "",
        ])

        if report.summary:
            lines.extend([
                f"- **Total Findings:** {report.summary.get('total', 0)}",
                f"- **Critical:** {report.summary.get('critical', 0)}",
                f"- **High:** {report.summary.get('high', 0)}",
                f"- **Medium:** {report.summary.get('medium', 0)}",
                f"- **Low:** {report.summary.get('low', 0)}",
                f"- **Info:** {report.summary.get('info', 0)}",
                "",
            ])

        # Scope
        if report.scope:
            lines.extend([
                "## Scope",
                "",
            ])
            for scope_item in report.scope:
                lines.append(f"- {scope_item}")
            lines.append("")

        # Vulnerabilities by severity
        severity_order = [
            Severity.CRITICAL,
            Severity.HIGH,
            Severity.MEDIUM,
            Severity.LOW,
            Severity.INFO,
        ]

        for severity in severity_order:
            vulns = [v for v in report.vulnerabilities if v.severity == severity]
            if not vulns:
                continue

            lines.extend([
                f"## {severity.value.upper()} Severity ({len(vulns)})",
                "",
            ])

            for vuln in vulns:
                lines.extend([
                    f"### {vuln.name}",
                    "",
                    f"**Type:** {vuln.type.value}",
                    f"**Target:** {vuln.target}",
                ])

                if vuln.url:
                    lines.append(f"**URL:** {vuln.url}")

                if vuln.cvss:
                    lines.append(f"**CVSS:** {vuln.cvss}")

                if vuln.cve:
                    lines.append(f"**CVE:** {vuln.cve}")

                lines.extend([
                    "",
                    f"### Description",
                    "",
                    vuln.description or "No description provided.",
                ])

                if vuln.impact:
                    lines.extend([
                        "",
                        f"### Impact",
                        "",
                        vuln.impact,
                    ])

                if vuln.remediation:
                    lines.extend([
                        "",
                        f"### Remediation",
                        "",
                        vuln.remediation,
                    ])

                if vuln.poc:
                    lines.extend([
                        "",
                        f"### Proof of Concept",
                        "",
                        "```",
                        vuln.poc,
                        "```",
                    ])

                if vuln.request:
                    lines.extend([
                        "",
                        "#### Request",
                        "",
                        "```http",
                        vuln.request,
                        "```",
                    ])

                if vuln.response:
                    lines.extend([
                        "",
                        "#### Response",
                        "",
                        "```http",
                        vuln.response,
                        "```",
                    ])

                if vuln.references:
                    lines.extend([
                        "",
                        "### References",
                        "",
                    ])
                    for ref in vuln.references:
                        lines.append(f"- {ref}")

                lines.append("")

        # Footer
        lines.extend([
            "---",
            "",
            "*Report generated by BugBounty MCP*",
        ])

        return "\n".join(lines)


class HTMLReporter:
    """Generate HTML vulnerability reports."""

    def __init__(self):
        self.template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <style>
        :root {
            --critical: #d32f2f;
            --high: #f57c00;
            --medium: #fbc02d;
            --low: #388e3c;
            --info: #1976d2;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            color: #333;
        }
        h1 { color: #1a1a1a; border-bottom: 2px solid #ddd; padding-bottom: 10px; }
        h2 { margin-top: 30px; color: #444; }
        h3 { color: #555; margin-top: 20px; }
        .meta { color: #666; font-size: 0.9em; }
        .severity {
            display: inline-block;
            padding: 4px 12px;
            border-radius: 4px;
            color: white;
            font-weight: bold;
            text-transform: uppercase;
            font-size: 0.8em;
        }
        .critical { background: var(--critical); }
        .high { background: var(--high); }
        .medium { background: var(--medium); color: #333; }
        .low { background: var(--low); }
        .info { background: var(--info); }
        .vuln-card {
            border: 1px solid #ddd;
            border-radius: 8px;
            padding: 20px;
            margin: 20px 0;
            background: #fafafa;
        }
        .summary {
            display: grid;
            grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
            gap: 15px;
            margin: 20px 0;
        }
        .summary-card {
            padding: 15px;
            border-radius: 8px;
            text-align: center;
            color: white;
        }
        .summary-card .count { font-size: 2em; font-weight: bold; }
        .summary-card .label { font-size: 0.9em; opacity: 0.9; }
        code {
            background: #f4f4f4;
            padding: 2px 6px;
            border-radius: 3px;
            font-family: 'Courier New', monospace;
        }
        pre {
            background: #f4f4f4;
            padding: 15px;
            border-radius: 5px;
            overflow-x: auto;
        }
        pre code { background: none; padding: 0; }
        .poc { background: #f0f0f0; }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th { background: #f5f5f5; }
    </style>
</head>
<body>
    <h1>{{ title }}</h1>
    <div class="meta">
        <p><strong>Target:</strong> {{ target }}</p>
        <p><strong>Date:</strong> {{ date }}</p>
        {% if author %}<p><strong>Author:</strong> {{ author }}</p>{% endif %}
    </div>

    <h2>Summary</h2>
    <div class="summary">
        <div class="summary-card critical">
            <div class="count">{{ summary.critical or 0 }}</div>
            <div class="label">Critical</div>
        </div>
        <div class="summary-card high">
            <div class="count">{{ summary.high or 0 }}</div>
            <div class="label">High</div>
        </div>
        <div class="summary-card medium">
            <div class="count">{{ summary.medium or 0 }}</div>
            <div class="label">Medium</div>
        </div>
        <div class="summary-card low">
            <div class="count">{{ summary.low or 0 }}</div>
            <div class="label">Low</div>
        </div>
        <div class="summary-card info">
            <div class="count">{{ summary.info or 0 }}</div>
            <div class="label">Info</div>
        </div>
    </div>

    {% for severity, vulns in by_severity.items() %}
    <h2>{{ severity|upper }} ({{ vulns|length }})</h2>
    {% for vuln in vulns %}
    <div class="vuln-card">
        <h3>{{ vuln.name }}</h3>
        <p>
            <span class="severity {{ severity }}">{{ severity }}</span>
            <strong>Type:</strong> {{ vuln.type.value }}
            <strong>Target:</strong> {{ vuln.target }}
            {% if vuln.cvss %}<strong>CVSS:</strong> {{ vuln.cvss }}{% endif %}
        </p>

        <h4>Description</h4>
        <p>{{ vuln.description }}</p>

        {% if vuln.impact %}
        <h4>Impact</h4>
        <p>{{ vuln.impact }}</p>
        {% endif %}

        {% if vuln.remediation %}
        <h4>Remediation</h4>
        <p>{{ vuln.remediation }}</p>
        {% endif %}

        {% if vuln.poc %}
        <h4>Proof of Concept</h4>
        <pre class="poc"><code>{{ vuln.poc }}</code></pre>
        {% endif %}
    </div>
    {% endfor %}
    {% endfor %}

    <footer style="margin-top: 40px; padding-top: 20px; border-top: 1px solid #ddd; color: #666;">
        <p>Report generated by BugBounty MCP</p>
    </footer>
</body>
</html>
"""

    def generate(self, report: Report) -> str:
        """Generate an HTML report."""
        from jinja2 import Template

        # Group vulnerabilities by severity
        by_severity: Dict[str, List[Vulnerability]] = {}
        for vuln in report.vulnerabilities:
            sev = vuln.severity.value
            if sev not in by_severity:
                by_severity[sev] = []
            by_severity[sev].append(vuln)

        template = Template(self.template)
        return template.render(
            title=report.title,
            target=report.target,
            date=report.created_at.strftime("%Y-%m-%d %H:%M:%S"),
            author=report.author,
            summary=report.summary,
            by_severity=by_severity,
        )


class JSONReporter:
    """Generate JSON vulnerability reports."""

    def generate(self, report: Report) -> str:
        """Generate a JSON report."""
        data = {
            "title": report.title,
            "target": report.target,
            "scope": report.scope,
            "created_at": report.created_at.isoformat(),
            "version": report.version,
            "author": report.author,
            "summary": report.summary,
            "vulnerabilities": [
                {
                    "id": v.id,
                    "name": v.name,
                    "type": v.type.value,
                    "severity": v.severity.value,
                    "target": v.target,
                    "url": v.url,
                    "description": v.description,
                    "impact": v.impact,
                    "remediation": v.remediation,
                    "cvss": v.cvss,
                    "cve": v.cve,
                    "cwe": v.cwe,
                    "poc": v.poc,
                    "request": v.request,
                    "response": v.response,
                    "references": v.references,
                    "tags": v.tags,
                    "discovered_at": v.discovered_at.isoformat(),
                }
                for v in report.vulnerabilities
            ],
        }

        return json.dumps(data, indent=2)


class Reporter:
    """Main reporting class that supports multiple formats."""

    def __init__(self):
        self.markdown = MarkdownReporter()
        self.html = HTMLReporter()
        self.json = JSONReporter()

    def generate_report(
        self,
        report: Report,
        format: str = "markdown",
    ) -> str:
        """Generate a report in the specified format."""
        generators = {
            "markdown": self.markdown.generate,
            "md": self.markdown.generate,
            "html": self.html.generate,
            "json": self.json.generate,
        }

        generator = generators.get(format.lower())
        if not generator:
            raise ValueError(f"Unknown format: {format}")

        return generator(report)

    async def save_report(
        self,
        report: Report,
        output_path: Path,
        format: str = "markdown",
    ) -> None:
        """Save a report to a file."""
        content = self.generate_report(report, format)
        output_path.write_text(content)

    async def save_all_formats(
        self,
        report: Report,
        output_dir: Path,
    ) -> Dict[str, Path]:
        """Save reports in all formats."""
        output_dir.mkdir(parents=True, exist_ok=True)

        base_name = self._sanitize_filename(report.title)
        outputs: Dict[str, Path] = {}

        formats = ["markdown", "html", "json"]
        extensions = {"markdown": "md", "html": "html", "json": "json"}

        for fmt in formats:
            ext = extensions[fmt]
            path = output_dir / f"{base_name}.{ext}"
            content = self.generate_report(report, fmt)
            path.write_text(content)
            outputs[fmt] = path

        return outputs

    def _sanitize_filename(self, name: str) -> str:
        """Sanitize a string for use as a filename."""
        import re
        name = re.sub(r"[^\w\s-]", "", name)
        name = re.sub(r"[-\s]+", "-", name)
        return name.strip("-")
